
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Версия MSBuild 17.7.2+d6990bcfa для .NET Framework
      Сборка начата 19.03.2024 20:54:53.
      
      Проект "C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        Обращение к "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Сборка проекта "C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:01.90
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/XOMA/Documents/GitHub/projects-2024/SFML2/CMakeFiles/3.28.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Версия MSBuild 17.7.2+d6990bcfa для .NET Framework
      Сборка начата 19.03.2024 20:54:55.
      
      Проект "C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        Обращение к "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Сборка проекта "C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:01.01
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/XOMA/Documents/GitHub/projects-2024/SFML2/CMakeFiles/3.28.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:6 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/XOMA/Documents/GitHub/projects-2024/SFML2/CMakeFiles/CMakeScratch/TryCompile-ue5fz4"
      binary: "C:/Users/XOMA/Documents/GitHub/projects-2024/SFML2/CMakeFiles/CMakeScratch/TryCompile-ue5fz4"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/XOMA/Documents/GitHub/projects-2024/SFML2/CMakeFiles/CMakeScratch/TryCompile-ue5fz4'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_d6594.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Версия MSBuild 17.7.2+d6990bcfa для .NET Framework
        Сборка начата 19.03.2024 20:54:57.
        
        Проект "C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\CMakeScratch\\TryCompile-ue5fz4\\cmTC_d6594.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_d6594.dir\\Debug\\".
          Создание каталога "C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\CMakeScratch\\TryCompile-ue5fz4\\Debug\\".
          Создание каталога "cmTC_d6594.dir\\Debug\\cmTC_d6594.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_d6594.dir\\Debug\\cmTC_d6594.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
          Обращение к "cmTC_d6594.dir\\Debug\\cmTC_d6594.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d6594.dir\\Debug\\\\" /Fd"cmTC_d6594.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.37.32824 для x64
          CMakeCCompilerABI.c
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d6594.dir\\Debug\\\\" /Fd"cmTC_d6594.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\CMakeScratch\\TryCompile-ue5fz4\\Debug\\cmTC_d6594.exe" /INCREMENTAL /ILK:"cmTC_d6594.dir\\Debug\\cmTC_d6594.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/XOMA/Documents/GitHub/projects-2024/SFML2/CMakeFiles/CMakeScratch/TryCompile-ue5fz4/Debug/cmTC_d6594.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/XOMA/Documents/GitHub/projects-2024/SFML2/CMakeFiles/CMakeScratch/TryCompile-ue5fz4/Debug/cmTC_d6594.lib" /MACHINE:X64  /machine:x64 cmTC_d6594.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_d6594.vcxproj -> C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\CMakeScratch\\TryCompile-ue5fz4\\Debug\\cmTC_d6594.exe
        FinalizeBuildStatus:
          Файл "cmTC_d6594.dir\\Debug\\cmTC_d6594.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_d6594.dir\\Debug\\cmTC_d6594.tlog\\cmTC_d6594.lastbuildstate".
        Сборка проекта "C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\CMakeScratch\\TryCompile-ue5fz4\\cmTC_d6594.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.96
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:6 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/XOMA/Documents/GitHub/projects-2024/SFML2/CMakeFiles/CMakeScratch/TryCompile-ai3wx9"
      binary: "C:/Users/XOMA/Documents/GitHub/projects-2024/SFML2/CMakeFiles/CMakeScratch/TryCompile-ai3wx9"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/XOMA/Documents/GitHub/projects-2024/SFML2/CMakeFiles/CMakeScratch/TryCompile-ai3wx9'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_985c2.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Версия MSBuild 17.7.2+d6990bcfa для .NET Framework
        Сборка начата 19.03.2024 20:54:59.
        
        Проект "C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\CMakeScratch\\TryCompile-ai3wx9\\cmTC_985c2.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_985c2.dir\\Debug\\".
          Создание каталога "C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\CMakeScratch\\TryCompile-ai3wx9\\Debug\\".
          Создание каталога "cmTC_985c2.dir\\Debug\\cmTC_985c2.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_985c2.dir\\Debug\\cmTC_985c2.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
          Обращение к "cmTC_985c2.dir\\Debug\\cmTC_985c2.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_985c2.dir\\Debug\\\\" /Fd"cmTC_985c2.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.37.32824 для x64
          CMakeCXXCompilerABI.cpp
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_985c2.dir\\Debug\\\\" /Fd"cmTC_985c2.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\CMakeScratch\\TryCompile-ai3wx9\\Debug\\cmTC_985c2.exe" /INCREMENTAL /ILK:"cmTC_985c2.dir\\Debug\\cmTC_985c2.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/XOMA/Documents/GitHub/projects-2024/SFML2/CMakeFiles/CMakeScratch/TryCompile-ai3wx9/Debug/cmTC_985c2.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/XOMA/Documents/GitHub/projects-2024/SFML2/CMakeFiles/CMakeScratch/TryCompile-ai3wx9/Debug/cmTC_985c2.lib" /MACHINE:X64  /machine:x64 cmTC_985c2.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_985c2.vcxproj -> C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\CMakeScratch\\TryCompile-ai3wx9\\Debug\\cmTC_985c2.exe
        FinalizeBuildStatus:
          Файл "cmTC_985c2.dir\\Debug\\cmTC_985c2.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_985c2.dir\\Debug\\cmTC_985c2.tlog\\cmTC_985c2.lastbuildstate".
        Сборка проекта "C:\\Users\\XOMA\\Documents\\GitHub\\projects-2024\\SFML2\\CMakeFiles\\CMakeScratch\\TryCompile-ai3wx9\\cmTC_985c2.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.98
        
      exitCode: 0
...
